name: Continuous Integration

on:
  push:
    branches: [ "develop", "release-*" ]

jobs:
  ci:
    name: Test - Unit & Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'

      - name: Unit & Integration Tests
        run: mvn -B verify

      - name: Sonar Analysis
        if: success()
        run: >
          mvn -B verify -DskipTests sonar:sonar
          -Dsonar.projectKey=zair-bulos_iwvg-devops-zair
          -Dsonar.organization=zair-bulos
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=$SONAR_TOKEN
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}